### ISSUE TITLE
License

### ISSUE THREAD

**Issue by lzap** [phemmer/ruby-syslogio#1]
Hello,

I created a patch https://github.com/thuehlinger/daemons/pull/43 pulling your work in. Are you willing to re-license this work under the project's license (BSD looks like): https://github.com/thuehlinger/daemons/blob/master/LICENSE

If you could drop a comment in the PR confirming, that would be fantastic. Thanks!

**Comment by phemmer** [comment]
Happy to help. I [added](https://github.com/phemmer/ruby-syslogio/commit/52401371af0aa1cd07120ac5fb50eafb36b5b3b6) [MIT license](https://github.com/phemmer/ruby-syslogio/blob/master/LICENSE) to the repo, as that's the license I use on all my stuff. Also dropped [a comment](https://github.com/thuehlinger/daemons/pull/43#issuecomment-154284786) on your PR

If there's anything else, just let me know :-)
